app:
  image: myjboss
  environment:
    SERVICE_80_NAME: http
    SERVICE_NAME: app
    SERVICE_TAGS: production
    SERVICE_PORT: 8080
  volumes:
   - ./cluster/Math-ear-1.0.ear:/jboss/standalone/deployments/Math-ear-1.0.ear
   - ./cluster/launch.sh:/jboss/bin/launch.sh
  working_dir: /jboss/bin/
  command: bash launch.sh  
  ports:
  - "8080"

lb:
  build: ./
  links:
  - consul
  ports:
  - "88:80"

consul:
  command: -server -bootstrap -advertise 172.17.0.1
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
