weba:
  build: .
  expose:
    - 80

webb:
  build: .
  expose:
    - 80

webc:
  build: .
  expose:
    - 80

haproxy:
  image: haproxy
  volumes:
   - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  links:
   - weba
   - webb
   - webc
  ports:
   - "80:80"
   - "70:70"

  expose:
   - "80"
   - "70"
