web:
  build: .
  environment:
    SERVICE_80_NAME: http
    SERVICE_NAME: web
    SERVICE_TAGS: production
    SERVICE_PORT: 80
  ports:
    - "80"
  #restart: always

myhaproxy:
  build: ./haproxy
  links:
   - consul
  ports:
   - "88:80"
   - "80"

consul:
  command: -server -bootstrap -advertise 172.17.0.1
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
