app:
  image: tomcat
  environment:
    SERVICE_80_NAME: http
    SERVICE_NAME: app
    SERVICE_TAGS: production
    SERVICE_PORT: 8080
  volumes:
   - /home/sam/Desktop/docker-loadbalancer/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - /home/sam/Desktop/docker-loadbalancer/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /home/sam/Desktop/docker-loadbalancer/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  ports:
  - "8080"

lb:
  build: ./
  links:
  - consul
  ports:
  - "88:80"

consul:
  command: -server -bootstrap -advertise 172.17.0.1
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: gliderlabs/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
